# Generated by Django 5.2.2 on 2025-07-11 15:14

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id_azienda', models.IntegerField(primary_key=True, serialize=False)),
                ('ragione_sociale', models.TextField(max_length=100)),
                ('partita_iva', models.TextField(max_length=11)),
                ('indirizzo', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id_piatto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('descrizione', models.CharField(max_length=255, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_cottura', django_mysql.models.EnumField(choices=[('breve', 'Breve'), ('medio', 'Medio'), ('lungo', 'Lungo')], null=True)),
                ('tipo_piatto', django_mysql.models.EnumField(choices=[('primo piatto', 'Primo'), ('secondo piatto', 'Secondo'), ('frutta', 'Frutta'), ('dessert', 'Dessert'), ('bevande', 'Bevanda')])),
                ('contorno', django_mysql.models.EnumField(choices=[('patate al forno', 'Patate'), ('verdure grigliate', 'Verdure'), ('insalata mista', 'Insalata')], null=True)),
                ('origine_frutta', django_mysql.models.EnumField(choices=[('locale', 'Locale'), ('esterna', 'Estera'), ('biologica', 'Biologica'), ('convenzionale', 'Convenzionale')], null=True)),
                ('tipo_dessert', django_mysql.models.EnumField(choices=[('gelato', 'Gelato'), ('torta', 'Torta'), ('budino', 'Budino'), ('semifreddo', 'Semifreddo')], null=True)),
                ('alcolica', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Responsabile',
            fields=[
                ('id_responsabile', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id_struttura', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('indirizzo', models.TextField(max_length=100)),
                ('numero_tavoli_disponibili', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Amministatore',
            fields=[
                ('id_amministratore', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.TextField(max_length=32)),
                ('id_azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amministratore', to='mensa.azienda')),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id_dipendente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('id_azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipendente', to='mensa.azienda')),
            ],
        ),
        migrations.CreateModel(
            name='Associazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.piatto')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id_prenotazione', models.AutoField(primary_key=True, serialize=False)),
                ('data_prenotazione', models.DateField()),
                ('fascia_oraria', models.CharField(choices=[('12:00-12:30', '12:00-12:30'), ('12:30-13:00', '12:30-13:00'), ('13:00-13:30', '13:00-13:30'), ('13:30-14:00', '13:30-14:00'), ('14:00-14:30', '14:00-14:30'), ('14:30-15:00', '14:30-15:00')], max_length=20)),
                ('stato', django_mysql.models.EnumField(choices=[('in attesa', 'In Attesa'), ('annullata', 'Annullata'), ('confermata', 'Confermata')], default='in attesa')),
                ('totale_prezzo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('id_dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazione', to='mensa.dipendente')),
                ('piatti', models.ManyToManyField(through='mensa.Associazione', to='mensa.piatto')),
            ],
        ),
        migrations.AddField(
            model_name='associazione',
            name='prenotazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mensa.prenotazione'),
        ),
        migrations.AddField(
            model_name='piatto',
            name='id_responsabile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piatto', to='mensa.responsabile'),
        ),
        migrations.AddField(
            model_name='responsabile',
            name='id_struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabile', to='mensa.struttura'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='id_struttura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azienda', to='mensa.struttura'),
        ),
        migrations.CreateModel(
            name='Tavolo',
            fields=[
                ('id_tavolo', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_posti_disponibili', models.IntegerField()),
                ('disponibilità', models.BooleanField(default=True)),
                ('struttura_associata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tavolo', to='mensa.struttura')),
            ],
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='id_tavolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazione', to='mensa.tavolo'),
        ),
    ]
